### ISSUE TITLE
中文时插件无法正确加载

### ISSUE THREAD

**Issue by JaveleyQAQ** [Leon406/BurpSuiteCN-Release#11]
中文时Hackvertor没有办法加载，虽然加载成功但是不展示UI，卸载插件时候提示
```
java.lang.NullPointerException: Cannot invoke "javax.swing.JMenuBar.remove(java.awt.Component)" because "this.burpMenuBar" is null	at burp.BurpExtender.extensionUnloaded(BurpExtender.java:1064)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	at java.base/java.lang.reflect.Method.invoke(Method.java:568)	at burp.Zlwv.invoke(Unknown Source)	at jdk.proxy2/jdk.proxy2.$Proxy22.extensionUnloaded(Unknown Source)	at burp.Zll7.ZT(Unknown Source)	at burp.Zndb.ZZ(Unknown Source)	at burp.Znsu.lambda$unloadExtension$19(Unknown Source)	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)	at java.base/java.lang.Thread.run(Thread.java:833)
```

控制台提示 
![image](https://github.com/Leon406/BurpSuiteCN-Release/assets/132129852/8283aa88-84e9-4ee3-bda3-bbe2347bfe90)

**Comment by JaveleyQAQ** [comment]
Whitelist outer file not exits: white.txt
burp loader class: burp.Znwo@3bbf6abe  class burp/cuw  method: s ([Ljava/lang/Object;Ljava/lang/Object;)V Hanzify By: Leon406 
Invalid line: Intruder    
Invalid line: Tags    标签
init state: literal 3882 regex 539 white 52 
Outer translate language file not exist: cn.txt
2023-05-19 21:26:03.230 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:03.231 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f3834a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2023-05-19 21:26:03.610 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:03.612 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f38213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
filter translate
filter translate
2023-05-19 21:26:09.923 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:09.924 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f38213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2023-05-19 21:26:12.234 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:12.235 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f38213 ReceiveNextEventCommon + 283
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
2023-05-19 21:26:12.918 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:12.919 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f3834a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java)
	at ch.pentagrid.burpexts.pentagridscancontroller.ScanUI$createUi$$inlined$schedule$1.run(Timer.kt:154)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.IndexOutOfBoundsException: No group 1
	at java.base/java.util.regex.Matcher.start(Matcher.java:482)
	at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1090)
	at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:997)
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1181)
	at leon406.Translator.translate(Translator.java:231)
	at leon406.Translator.translate(Translator.java:204)
	... 7 more
2023-05-19 21:26:25.886 java[7086:148612] Bad JNI lookup accessibilityHitTest
2023-05-19 21:26:25.888 java[7086:148612] (
	0   libawt_lwawt.dylib                  0x0000000138db497d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x0000000138d6f280 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff81f5607be -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff81f0f3bcb -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 285
	4   AppKit                              0x00007ff81f0c359c CopyElementAtPosition + 136
	5   HIServices                          0x00007ff821d235da _AXXMIGCopyElementAtPosition + 393
	6   HIServices                          0x00007ff821d44ec4 _XCopyElementAtPosition + 355
	7   HIServices                          0x00007ff821d02729 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff81c28b924 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff81c28b804 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff81c289e6b __CFRunLoopRun + 2415
	11  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	12  HIToolbox                           0x00007ff824f385e6 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff824f3834a ReceiveNextEventCommon + 594
	14  HIToolbox                           0x00007ff824f380e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff81ecc2fad _DPSNextEvent + 927
	16  AppKit                              0x00007ff81ecc166a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	17  libosxapp.dylib                     0x000000010bbc856a -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff81ecb3d19 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x000000010bbc8339 +[NSApplicationAWT runAWTLoopWithApp:] + 169
	20  libsplashscreen.dylib               0x000000010bc49819 __SplashInitPlatform_block_invoke + 73
	21  libosxapp.dylib                     0x000000010bbca00f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff81d108527 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff81c28b17b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff81c28b0e3 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff81c28ae5d __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff81c289878 __CFRunLoopRun + 892
	27  CoreFoundation                      0x00007ff81c288e3c CFRunLoopRunSpecific + 562
	28  libjli.dylib                        0x000000010aff70b2 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010aff2c15 JLI_Launch + 1413
	30  java                                0x000000010aecac09 main + 393
	31  dyld                                0x0000000117a2952e start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 20
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.desktop/javax.swing.JTabbedPane.getTitleAt(JTabbedPane.java:1155)
	at burp.ui.HackvertorPanel$17.stateChanged(HackvertorPanel.java:489)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:444)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:648)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:623)
	at burp.ui.HackvertorPanel.buildTabbedPane(HackvertorPanel.java:498)
	at burp.ui.HackvertorPanel.buildPanel(HackvertorPanel.java:80)
	at burp.ui.HackvertorPanel.<init>(HackvertorPanel.java:58)
	at burp.ui.ExtensionPanel.<init>(ExtensionPanel.java:32)
	at burp.BurpExtender$2.run(BurpExtender.java:209)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.desktop/javax.swing.DefaultRowSorter.convertRowIndexToModel(DefaultRowSorter.java:508)
	at java.desktop/javax.swing.JTable.convertRowIndexToModel(JTable.java:2686)
	at ui.ScanStatusTable.changeSelection(ScanStatusTable.kt:30)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI$Actions.actionPerformed(BasicTableUI.java:581)
	at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
	at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2947)
	at java.desktop/javax.swing.JTable.processKeyBinding(JTable.java:5321)
	at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:3009)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2909)
	at java.desktop/java.awt.Component.processEvent(Component.java:6403)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1952)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:883)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1150)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:848)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4882)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-05-19 21:28:36.667 java[7086:148612] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

**Comment by Leon406** [comment]
https://stackoverflow.com/questions/73077071/bad-jni-lookup-accessibilityhittest-what-does-this-unexpected-error-message-me

**Comment by JaveleyQAQ** [comment]
> https://stackoverflow.com/questions/73077071/bad-jni-lookup-accessibilityhittest-what-does-this-unexpected-error-message-me
> 
> 有没有可能是插件与jdk版本的兼容问题呢

我不汉化是没事的，汉化了就报了，即使是不加载这个插件

**Comment by Leon406** [comment]
https://leon.lanzoub.com/iJK6F0wn4s2f
先用这个版本, 目前windows测试正常,
翻译插件中不该翻译的内容,加入过滤

**Comment by JaveleyQAQ** [comment]
> https://leon.lanzoub.com/iJK6F0wn4s2f 先用这个版本, 目前windows测试正常, 翻译插件中不该翻译的内容,加入过滤

可以的

**Comment by Leon406** [comment]
Hackvertor插件实现问题, 不能对20个标签功能文本进行翻译, 
cn默认会对 Compression|Custom|Encode|Decode|Search 进行翻译
导致找不到内容
