### ISSUE TITLE
jdk

### ISSUE THREAD

**Issue by HY-November** [Leon406/BurpSuiteCN-Release#13]
好像不兼容最新的Jdk

**Comment by Leon406** [comment]
什么问题, 之前好像测试过jdk20是可以的

**Comment by HY-November** [comment]
state false args []
Exception in thread "main" java.lang.NumberFormatException: For input string: "21-ea"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:661)
        at java.base/java.lang.Integer.parseInt(Integer.java:777)
        at leon406.util.CommonUtil.getLaunchCommand(CommonUtil.java:102)
        at leon406.KeygenDialog.setupUI(KeygenDialog.java:100)
        at leon406.KeygenDialog.<init>(KeygenDialog.java:28)
        at leon406.KeygenDialog.showKenGenDialog(KeygenDialog.java:73)
        at leon406.KeygenDialog.main(KeygenDialog.java:61)
这是什么意思

**Comment by Leon406** [comment]
怎么用ea版本.. 

建议用 jdk17
或者改成配置java-agent方式执行

**Comment by HY-November** [comment]
换到jdk19就解决了
